//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessAcessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLNSEntities : DbContext
    {
        public QLNSEntities()
            : base("name=QLNSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHDBan> ChiTietHDBans { get; set; }
        public virtual DbSet<ChiTietHoaDonNhap> ChiTietHoaDonNhaps { get; set; }
        public virtual DbSet<HoaDonBan> HoaDonBans { get; set; }
        public virtual DbSet<HoaDonNhap> HoaDonNhaps { get; set; }
        public virtual DbSet<NXB> NXBs { get; set; }
        public virtual DbSet<NhaCC> NhaCCs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TacGiaVietSach> TacGiaVietSaches { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TheLoai> TheLoais { get; set; }
        public virtual DbSet<VW_DanhSachSachDaBan> VW_DanhSachSachDaBan { get; set; }
        public virtual DbSet<VW_DanhSachTheLoaiDaBan> VW_DanhSachTheLoaiDaBan { get; set; }
        public virtual DbSet<VW_ChiTietHDBan> VW_ChiTietHDBan { get; set; }
        public virtual DbSet<VW_HoaDonBan> VW_HoaDonBan { get; set; }
        public virtual DbSet<VW_ChiTietHDNhap> VW_ChiTietHDNhap { get; set; }
        public virtual DbSet<VW_HoaDonNhap> VW_HoaDonNhap { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int spCapNhatLaiSoLuongSach(string maSach, Nullable<int> soLuongThem)
        {
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var soLuongThemParameter = soLuongThem.HasValue ?
                new ObjectParameter("SoLuongThem", soLuongThem) :
                new ObjectParameter("SoLuongThem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCapNhatLaiSoLuongSach", maSachParameter, soLuongThemParameter);
        }
    
        public virtual int spDeleteAllTacGiaVietSach(string maSach)
        {
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteAllTacGiaVietSach", maSachParameter);
        }
    
        public virtual int spDeleteChiTietHDBan(string maHDB, string maSach)
        {
            var maHDBParameter = maHDB != null ?
                new ObjectParameter("MaHDB", maHDB) :
                new ObjectParameter("MaHDB", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteChiTietHDBan", maHDBParameter, maSachParameter);
        }
    
        public virtual int spDeleteChiTietHDNhap(string maHDN, string maSach)
        {
            var maHDNParameter = maHDN != null ?
                new ObjectParameter("MaHDN", maHDN) :
                new ObjectParameter("MaHDN", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteChiTietHDNhap", maHDNParameter, maSachParameter);
        }
    
        public virtual int spDeleteHoaDonBan(string maHDB)
        {
            var maHDBParameter = maHDB != null ?
                new ObjectParameter("MaHDB", maHDB) :
                new ObjectParameter("MaHDB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteHoaDonBan", maHDBParameter);
        }
    
        public virtual int spDeleteHoaDonNhap(string maHDN)
        {
            var maHDNParameter = maHDN != null ?
                new ObjectParameter("MaHDN", maHDN) :
                new ObjectParameter("MaHDN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteHoaDonNhap", maHDNParameter);
        }
    
        public virtual int spDeleteTaiKhoan(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteTaiKhoan", maNVParameter);
        }
    
        public virtual int spInsertChiTietHDBan(string maHDB, string maSach, Nullable<int> soLuong)
        {
            var maHDBParameter = maHDB != null ?
                new ObjectParameter("MaHDB", maHDB) :
                new ObjectParameter("MaHDB", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertChiTietHDBan", maHDBParameter, maSachParameter, soLuongParameter);
        }
    
        public virtual int spInsertChiTietHDNhap(string maHDN, string maSach, Nullable<int> soLuong, Nullable<double> giaNhap)
        {
            var maHDNParameter = maHDN != null ?
                new ObjectParameter("MaHDN", maHDN) :
                new ObjectParameter("MaHDN", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var giaNhapParameter = giaNhap.HasValue ?
                new ObjectParameter("GiaNhap", giaNhap) :
                new ObjectParameter("GiaNhap", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertChiTietHDNhap", maHDNParameter, maSachParameter, soLuongParameter, giaNhapParameter);
        }
    
        public virtual int spInsertHoaDonBan(string maHDB, string maNV, string hoTenKH, Nullable<System.DateTime> ngayLapHD)
        {
            var maHDBParameter = maHDB != null ?
                new ObjectParameter("MaHDB", maHDB) :
                new ObjectParameter("MaHDB", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoTenKHParameter = hoTenKH != null ?
                new ObjectParameter("HoTenKH", hoTenKH) :
                new ObjectParameter("HoTenKH", typeof(string));
    
            var ngayLapHDParameter = ngayLapHD.HasValue ?
                new ObjectParameter("NgayLapHD", ngayLapHD) :
                new ObjectParameter("NgayLapHD", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertHoaDonBan", maHDBParameter, maNVParameter, hoTenKHParameter, ngayLapHDParameter);
        }
    
        public virtual int spInsertHoaDonNhap(string maHDN, string maNCC, string maNV, Nullable<System.DateTime> ngayLap)
        {
            var maHDNParameter = maHDN != null ?
                new ObjectParameter("MaHDN", maHDN) :
                new ObjectParameter("MaHDN", typeof(string));
    
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertHoaDonNhap", maHDNParameter, maNCCParameter, maNVParameter, ngayLapParameter);
        }
    
        public virtual int spInsertNhaCC(string maNCC, string tenNCC, string diaChi, string sDT, Nullable<bool> tinhTrang)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var tenNCCParameter = tenNCC != null ?
                new ObjectParameter("TenNCC", tenNCC) :
                new ObjectParameter("TenNCC", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertNhaCC", maNCCParameter, tenNCCParameter, diaChiParameter, sDTParameter, tinhTrangParameter);
        }
    
        public virtual int spInsertNhanVien(string maNV, string hoNV, string tenNV, Nullable<System.DateTime> ngaySinh, Nullable<bool> nu, Nullable<System.DateTime> ngayNV, string diaChi, string soDT, Nullable<double> luong, Nullable<bool> tinhTrang)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoNVParameter = hoNV != null ?
                new ObjectParameter("HoNV", hoNV) :
                new ObjectParameter("HoNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var nuParameter = nu.HasValue ?
                new ObjectParameter("Nu", nu) :
                new ObjectParameter("Nu", typeof(bool));
    
            var ngayNVParameter = ngayNV.HasValue ?
                new ObjectParameter("NgayNV", ngayNV) :
                new ObjectParameter("NgayNV", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDTParameter = soDT != null ?
                new ObjectParameter("SoDT", soDT) :
                new ObjectParameter("SoDT", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(double));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertNhanVien", maNVParameter, hoNVParameter, tenNVParameter, ngaySinhParameter, nuParameter, ngayNVParameter, diaChiParameter, soDTParameter, luongParameter, tinhTrangParameter);
        }
    
        public virtual int spInsertNXB(string maNXB, string tenNXB, Nullable<bool> tinhTrang)
        {
            var maNXBParameter = maNXB != null ?
                new ObjectParameter("MaNXB", maNXB) :
                new ObjectParameter("MaNXB", typeof(string));
    
            var tenNXBParameter = tenNXB != null ?
                new ObjectParameter("TenNXB", tenNXB) :
                new ObjectParameter("TenNXB", typeof(string));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertNXB", maNXBParameter, tenNXBParameter, tinhTrangParameter);
        }
    
        public virtual int spInsertSach(string maSach, string tenSach, string maTheLoai, string maNXB, Nullable<double> giaBan, Nullable<int> soLuongTon, Nullable<bool> tinhTrang)
        {
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var tenSachParameter = tenSach != null ?
                new ObjectParameter("TenSach", tenSach) :
                new ObjectParameter("TenSach", typeof(string));
    
            var maTheLoaiParameter = maTheLoai != null ?
                new ObjectParameter("MaTheLoai", maTheLoai) :
                new ObjectParameter("MaTheLoai", typeof(string));
    
            var maNXBParameter = maNXB != null ?
                new ObjectParameter("MaNXB", maNXB) :
                new ObjectParameter("MaNXB", typeof(string));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(double));
    
            var soLuongTonParameter = soLuongTon.HasValue ?
                new ObjectParameter("SoLuongTon", soLuongTon) :
                new ObjectParameter("SoLuongTon", typeof(int));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertSach", maSachParameter, tenSachParameter, maTheLoaiParameter, maNXBParameter, giaBanParameter, soLuongTonParameter, tinhTrangParameter);
        }
    
        public virtual int spInsertTacGiaVietSach(string maSach, string tenTacGia)
        {
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var tenTacGiaParameter = tenTacGia != null ?
                new ObjectParameter("TenTacGia", tenTacGia) :
                new ObjectParameter("TenTacGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertTacGiaVietSach", maSachParameter, tenTacGiaParameter);
        }
    
        public virtual int spInsertTaiKhoan(string maNV, string matKhau, Nullable<bool> quyen)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var quyenParameter = quyen.HasValue ?
                new ObjectParameter("Quyen", quyen) :
                new ObjectParameter("Quyen", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertTaiKhoan", maNVParameter, matKhauParameter, quyenParameter);
        }
    
        public virtual int spInsertTheLoai(string maTheLoai, string tenTheLoai, Nullable<bool> tinhTrang)
        {
            var maTheLoaiParameter = maTheLoai != null ?
                new ObjectParameter("MaTheLoai", maTheLoai) :
                new ObjectParameter("MaTheLoai", typeof(string));
    
            var tenTheLoaiParameter = tenTheLoai != null ?
                new ObjectParameter("TenTheLoai", tenTheLoai) :
                new ObjectParameter("TenTheLoai", typeof(string));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertTheLoai", maTheLoaiParameter, tenTheLoaiParameter, tinhTrangParameter);
        }
    
        public virtual int spUpdateChiTietHDBan(string maHDB, string maSach, Nullable<int> soLuong)
        {
            var maHDBParameter = maHDB != null ?
                new ObjectParameter("MaHDB", maHDB) :
                new ObjectParameter("MaHDB", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateChiTietHDBan", maHDBParameter, maSachParameter, soLuongParameter);
        }
    
        public virtual int spUpdateChiTietHDNhap(string maHDN, string maSach, Nullable<int> soLuong, Nullable<double> giaNhap)
        {
            var maHDNParameter = maHDN != null ?
                new ObjectParameter("MaHDN", maHDN) :
                new ObjectParameter("MaHDN", typeof(string));
    
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var giaNhapParameter = giaNhap.HasValue ?
                new ObjectParameter("GiaNhap", giaNhap) :
                new ObjectParameter("GiaNhap", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateChiTietHDNhap", maHDNParameter, maSachParameter, soLuongParameter, giaNhapParameter);
        }
    
        public virtual int spUpdateHoaDonBan(string maHDB, string maNV, string hoTenKH, Nullable<System.DateTime> ngayLapHD)
        {
            var maHDBParameter = maHDB != null ?
                new ObjectParameter("MaHDB", maHDB) :
                new ObjectParameter("MaHDB", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoTenKHParameter = hoTenKH != null ?
                new ObjectParameter("HoTenKH", hoTenKH) :
                new ObjectParameter("HoTenKH", typeof(string));
    
            var ngayLapHDParameter = ngayLapHD.HasValue ?
                new ObjectParameter("NgayLapHD", ngayLapHD) :
                new ObjectParameter("NgayLapHD", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateHoaDonBan", maHDBParameter, maNVParameter, hoTenKHParameter, ngayLapHDParameter);
        }
    
        public virtual int spUpdateHoaDonNhap(string maHDN, string maNCC, string maNV, Nullable<System.DateTime> ngayLap)
        {
            var maHDNParameter = maHDN != null ?
                new ObjectParameter("MaHDN", maHDN) :
                new ObjectParameter("MaHDN", typeof(string));
    
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateHoaDonNhap", maHDNParameter, maNCCParameter, maNVParameter, ngayLapParameter);
        }
    
        public virtual int spUpdateNhaCC(string maNCC, string tenNCC, string diaChi, string sDT, Nullable<bool> tinhTrang)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var tenNCCParameter = tenNCC != null ?
                new ObjectParameter("TenNCC", tenNCC) :
                new ObjectParameter("TenNCC", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateNhaCC", maNCCParameter, tenNCCParameter, diaChiParameter, sDTParameter, tinhTrangParameter);
        }
    
        public virtual int spUpdateNhanVien(string maNV, string hoNV, string tenNV, Nullable<System.DateTime> ngaySinh, Nullable<bool> nu, Nullable<System.DateTime> ngayNV, string diaChi, string soDT, Nullable<double> luong, Nullable<bool> tinhTrang)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoNVParameter = hoNV != null ?
                new ObjectParameter("HoNV", hoNV) :
                new ObjectParameter("HoNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var nuParameter = nu.HasValue ?
                new ObjectParameter("Nu", nu) :
                new ObjectParameter("Nu", typeof(bool));
    
            var ngayNVParameter = ngayNV.HasValue ?
                new ObjectParameter("NgayNV", ngayNV) :
                new ObjectParameter("NgayNV", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDTParameter = soDT != null ?
                new ObjectParameter("SoDT", soDT) :
                new ObjectParameter("SoDT", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(double));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateNhanVien", maNVParameter, hoNVParameter, tenNVParameter, ngaySinhParameter, nuParameter, ngayNVParameter, diaChiParameter, soDTParameter, luongParameter, tinhTrangParameter);
        }
    
        public virtual int spUpdateNXB(string maNXB, string tenNXB, Nullable<bool> tinhTrang)
        {
            var maNXBParameter = maNXB != null ?
                new ObjectParameter("MaNXB", maNXB) :
                new ObjectParameter("MaNXB", typeof(string));
    
            var tenNXBParameter = tenNXB != null ?
                new ObjectParameter("TenNXB", tenNXB) :
                new ObjectParameter("TenNXB", typeof(string));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateNXB", maNXBParameter, tenNXBParameter, tinhTrangParameter);
        }
    
        public virtual int spUpdateSach(string maSach, string tenSach, string maTheLoai, string maNXB, Nullable<double> giaBan, Nullable<int> soLuongTon, Nullable<bool> tinhTrang)
        {
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var tenSachParameter = tenSach != null ?
                new ObjectParameter("TenSach", tenSach) :
                new ObjectParameter("TenSach", typeof(string));
    
            var maTheLoaiParameter = maTheLoai != null ?
                new ObjectParameter("MaTheLoai", maTheLoai) :
                new ObjectParameter("MaTheLoai", typeof(string));
    
            var maNXBParameter = maNXB != null ?
                new ObjectParameter("MaNXB", maNXB) :
                new ObjectParameter("MaNXB", typeof(string));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(double));
    
            var soLuongTonParameter = soLuongTon.HasValue ?
                new ObjectParameter("SoLuongTon", soLuongTon) :
                new ObjectParameter("SoLuongTon", typeof(int));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateSach", maSachParameter, tenSachParameter, maTheLoaiParameter, maNXBParameter, giaBanParameter, soLuongTonParameter, tinhTrangParameter);
        }
    
        public virtual int spUpdateTaiKhoan(string maNV, string matKhau, Nullable<bool> quyen)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var quyenParameter = quyen.HasValue ?
                new ObjectParameter("Quyen", quyen) :
                new ObjectParameter("Quyen", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateTaiKhoan", maNVParameter, matKhauParameter, quyenParameter);
        }
    
        public virtual int spUpdateTheLoai(string maTheLoai, string tenTheLoai, Nullable<bool> tinhTrang)
        {
            var maTheLoaiParameter = maTheLoai != null ?
                new ObjectParameter("MaTheLoai", maTheLoai) :
                new ObjectParameter("MaTheLoai", typeof(string));
    
            var tenTheLoaiParameter = tenTheLoai != null ?
                new ObjectParameter("TenTheLoai", tenTheLoai) :
                new ObjectParameter("TenTheLoai", typeof(string));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateTheLoai", maTheLoaiParameter, tenTheLoaiParameter, tinhTrangParameter);
        }
    }
}
