//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessAcessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DanhSachTheLoaiDaBan
    {
        public string MaTheLoai { get; set; }
        public string TenTheLoai { get; set; }
        public Nullable<double> DoanhThu { get; set; }
    }
}
