//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessAcessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HoaDonNhap
    {
        public string MaHDN { get; set; }
        public string MaNV { get; set; }
        public string HoTenNV { get; set; }
        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
        public Nullable<double> TongChi { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    }
}
